"""add question types, matching pairs, and update answer model

Revision ID: 98940cc83df2
Revises: daece5e20800
Create Date: 2026-03-20 21:40:27.112335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98940cc83df2'
down_revision = 'daece5e20800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('matching_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('left_text', sa.String(length=200), nullable=False),
    sa.Column('right_text', sa.String(length=200), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_answer', sa.Text(), nullable=True))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('correct_answer_text', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'question_types', ['type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('correct_answer_text')
        batch_op.drop_column('type_id')

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_column('text_answer')

    op.drop_table('matching_pairs')
    op.drop_table('question_types')
    # ### end Alembic commands ###
